[package]
name = "eef-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.9.0"
native-dialog = "0.6.3"
rfd = "*"
serde_json = "1.0"
pyo3 = { version = "0.18.3", features = ["extension-module"] }